name: thebuzzlab.
favicon: null
layout_spectrum: 0.20152445905841887
typography_spectrum: 0.6484820276964456
title: Video. Strategy. Science.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff7200'
    - '#e4e4e4'
    - '#181818'
    - '#713200'
    - '#afafaf'
  brandStrength: 0.5625
  lightness: 0.45022325520403683
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
