name: The Buzz Lab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6484820276964456
title: Video. Strategy. Science.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0feff'
    - '#211b3d'
    - '#de9c6a'
    - '#90394a'
    - '#92676e'
  brandStrength: 0.6875
  lightness: 0.45022325520403683
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
