name: thebuzzlab.
favicon: null
layout_spectrum: 0.20152445905841887
typography_spectrum: 0.6484820276964456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9338040216825902
  lightness: 0.45022325520403683
  saturation: 0.5534978373907506
  rhythmicContrast: 0.680441931122914
purpose: []
